import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../../app/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   <div>

    <h2>Auth layout</h2>
    {
        children
    }


   </div>
  );
}
