import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../app/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  Users,
  news,
  analytics,
  children,
}: {
  Users: React.ReactNode;
  news: React.ReactNode;
  analytics: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="bg-red-200">
      <div>{children}</div>
      <div className="flex flex-row bg-slate-500 flex-1">
        <div className="flex flex-col bg-stone-500">
          
          {Users}
         
          {news}
        </div>
        <div
          style={{
            flex: 1,
          }}
        >
          {analytics}
        </div>
      </div>
    </div>
  );
}
