import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../../app/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: 'black',
          width: '100%',
          padding: '1px',
          margin:"0px",
        
        }}>
          <p style={{
            color: 'white',
            fontSize: '1.5rem',
          }}>{metadata.title}</p>
         
        </header>
        {children}</body>
    </html>
  )
}
